name: zip folder

on:
  push:
    paths:
      - 'static/**'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: static/
          dest: static.zip